### ISSUE TITLE
Support debug=tests

### ISSUE THREAD

**Issue by mart-e** [pga-odoo/OdooDebug#3]
See odoo/odoo@d6847bacb1d2425466003985f9e96837f22c2148
In 13.0, will now have 4 different debug mode:
- `debug=1` (simple debug)
- `debug=assets` (full js/css files)
- `debug=tests` (add js test files)
- `debug=assets,tests` (both above)

How should we handle this?
Maybe have something like `ctrl + .` to toggle classic debug and `ctrl + /` (or other) to toggle debug test mode (if already in debug=assets when adding test, would switch in `assets,tests`).

Too complicated?

**Comment by mart-e** [comment]
Most importantly, which icon? :thinking:

**Comment by jat-odoo** [comment]
@mart-e We have merged Odoo v13 compatibility https://github.com/pga-odoo/OdooDebug/pull/6.
Can you update Firefox extension?
Thanks for reporting :+1:.
